de_medallion_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'airflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'airflow') }}"
      dbname: gold
      schema: gold
      threads: 4
